---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 192.168.200.100 manager
        - 192.168.200.101 worker01
        - 192.168.200.102 worker02
        - 192.168.200.103 registry
        
    - name: Ajustando .bashrc do usuário vagrant
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'sudo su - suporte'

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Instalando pacotes de dependencias para o curso de Docker
      apt:
        name: ['unzip', 'wget', 'elinks', 'rsync', 'docker-ce', 'docker-ce-cli', 'containerd.io']

    - name: Startando Docker e habilitando servico
      service:
        name: docker
        state: started
        enabled: yes

    - name: Adicionar usuário suporte
      user:
        name: suporte
        groups: docker
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Criando o arquivo 98_4linux
      copy:
        src: files/98_4linux
        dest: /etc/sudoers.d
        mode: 0644

    - name: Criando diretório scripts
      synchronize:
        src: files/worker02/scripts
        dest: /home/suporte        
       
    - name: Definir permissão de acesso da HOME do usuario suporte
      file:
        path: /home/suporte
        owner: suporte
        group: suporte
        state: directory
        recurse: yes
        mode: 0755
